import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export const generatePDF = async (projectData: any, userData: any) => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let yPosition = 20;

  // Add title
  pdf.setFontSize(24);
  pdf.setTextColor(44, 82, 130);
  pdf.text('Your Kitchen Remodel Plan', pageWidth / 2, yPosition, { align: 'center' });
  yPosition += 20;

  // Add customer info
  pdf.setFontSize(12);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Prepared for: ${userData.name}`, 20, yPosition);
  yPosition += 8;
  pdf.text(`Email: ${userData.email}`, 20, yPosition);
  yPosition += 8;
  if (userData.zip) {
    pdf.text(`ZIP Code: ${userData.zip}`, 20, yPosition);
    yPosition += 8;
  }
  pdf.text(`Generated: ${new Date().toLocaleDateString()}`, 20, yPosition);
  yPosition += 20;

  // Add room planning section
  pdf.setFontSize(16);
  pdf.setTextColor(44, 82, 130);
  pdf.text('Room Planning', 20, yPosition);
  yPosition += 10;
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Dimensions: ${projectData.room_width}' × ${projectData.room_length}' (${projectData.room_height}' ceiling)`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Layout: ${projectData.layout_type.replace('-', ' ')} layout`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Linear Footage: ${projectData.linear_footage} feet`, 20, yPosition);
  yPosition += 15;

  // Add cabinet design section
  pdf.setFontSize(16);
  pdf.setTextColor(44, 82, 130);
  pdf.text('Cabinet Design', 20, yPosition);
  yPosition += 10;
  
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  pdf.text(`Style: ${projectData.cabinet_style.replace('-', ' ')}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Material: ${projectData.cabinet_material}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Hardware: ${projectData.hardware_type.replace('-', ' ')}`, 20, yPosition);
  yPosition += 6;
  pdf.text(`Upper Cabinets: ${projectData.upper_percentage}%`, 20, yPosition);
  yPosition += 15;

  // Add cost estimate section
  pdf.setFontSize(16);
  pdf.setTextColor(44, 82, 130);
  pdf.text('Cost Estimate', 20, yPosition);
  yPosition += 10;

  const estimate = projectData.estimate;
  
  // Create table-like structure
  pdf.setFontSize(11);
  pdf.setTextColor(0, 0, 0);
  
  // Headers
  pdf.text('Component', 20, yPosition);
  pdf.text('Budget', 90, yPosition);
  pdf.text('Recommended', 130, yPosition);
  pdf.text('Premium', 170, yPosition);
  yPosition += 8;

  // Draw line
  pdf.line(20, yPosition - 2, pageWidth - 20, yPosition - 2);
  yPosition += 2;

  // Cabinets row
  pdf.text('Cabinets', 20, yPosition);
  pdf.text(`$${estimate.cabinet_cost_low.toLocaleString()}`, 90, yPosition);
  pdf.text(`$${estimate.cabinet_cost_med.toLocaleString()}`, 130, yPosition);
  pdf.text(`$${estimate.cabinet_cost_high.toLocaleString()}`, 170, yPosition);
  yPosition += 8;

  // Installation row
  pdf.text('Installation', 20, yPosition);
  pdf.text(`$${estimate.labor_cost_low.toLocaleString()}`, 90, yPosition);
  pdf.text(`$${estimate.labor_cost_med.toLocaleString()}`, 130, yPosition);
  pdf.text(`$${estimate.labor_cost_high.toLocaleString()}`, 170, yPosition);
  yPosition += 8;

  // Total row
  pdf.line(20, yPosition - 2, pageWidth - 20, yPosition - 2);
  pdf.setFontSize(12);
  pdf.text('Total Project Cost', 20, yPosition + 3);
  pdf.text(`$${estimate.total_low.toLocaleString()}`, 90, yPosition + 3);
  pdf.text(`$${estimate.total_med.toLocaleString()}`, 130, yPosition + 3);
  pdf.text(`$${estimate.total_high.toLocaleString()}`, 170, yPosition + 3);
  yPosition += 20;

  // Add contractors section if available
  if (projectData.selectedContractors && projectData.selectedContractors.length > 0) {
    pdf.setFontSize(16);
    pdf.setTextColor(44, 82, 130);
    pdf.text('Contractor RFQ Status', 20, yPosition);
    yPosition += 10;
    
    pdf.setFontSize(11);
    pdf.setTextColor(0, 0, 0);
    pdf.text(`RFQ sent to ${projectData.selectedContractors.length} pre-qualified contractors`, 20, yPosition);
    yPosition += 6;
    pdf.text('Expect responses within 2-3 business days', 20, yPosition);
    yPosition += 15;
  }

  // Add footer
  pdf.setFontSize(10);
  pdf.setTextColor(128, 128, 128);
  pdf.text('Generated by Renova', pageWidth / 2, pageHeight - 20, { align: 'center' });
  pdf.text('www.renova.com | hello@renova.com', pageWidth / 2, pageHeight - 10, { align: 'center' });

  // Save the PDF
  pdf.save(`kitchen-remodel-plan-${userData.name.replace(/\s+/g, '-').toLowerCase()}.pdf`);
};